# ZuHa is a complete business management system on an MVC framework for maximum ease and expandability.

Our primary goal is to provide a single system that handles your business process from start to finish.  From leads generated by your website, to tracking those leads through your sales funnel, all the way to managing and fulfilling service and product requests.  

We further seek to solve the problem faced by many website systems, where in order to have multiple functions (like ecommerce, CRM, CMS, project management, social networking, groups, messaging, multi-user blogs, forums, events, wikis or any combination of those sub systems), you would at a minimum be forced to combine 2 systems or more into one by somehow convincing the two (or more) systems to talk each other. 


## Installation Tips

* Upload the files to the root directory 
 
* Ceate a database.php file in ROOT/app/config/ using ROOT/app/config/database.default.php as a template, fixing the variables with correct values. 
 
* Import ROOT/database.sql - latest bare database dump (maybe some testing data) included.
 
* ZuHa works best when installed at a root domain or subdomain of a site.  (ex. myDomain.com OR subDomain.myDomain.com OR subDomain.localhost).
 
* It is possible to get it to get a Hello World setup inside a sub directory, but you must rename or delete the ROOT/.htaccess file.  However, please note : webroot files (css / js / etc) will not work without further customization.  So its virtually worthless to use it in sub directories.
 
* Once you have a working view of the site you can login with the user "admin" and the password "test" in order to gain access to every available page. 
 
 
 
## Documentation

[ZuHa Foundation](http://zuha.com/) - promoting development related to ZuHa

[ZuHa Book](http://book.zuha.com/)

[ZuHa RoadMap Wiki](https://cakeforge.org/plugins/wiki/index.php?ProjectRoadMap&id=392&type=g)

[ZuHa Forum](https://cakeforge.org/forum/?group_id=392)

[About ZuHa](http://zuha.com/about)

[ZuHa on CakeForge](https://cakeforge.org/projects/zuha/)

[CakePHP](http://www.cakephp.org) - the rapid development PHP framework

[CakePHP Cookbook](http://book.cakephp.org) - user documentation for learning about CakePHP



## Reporting issues

[Submit Issues on Github.com](https://github.com/zuha/zuha/issues) 

## Versions

Pre-alpha

## License

GPL Version 3 (and future versions)