<?php
/**
 * Settings Model
 *
 * This database table contains all of the settings for the site, but its important to note that it is never called on by the application.  Instead every time you create or edit a setting, it updates a static file in the config folder called settings.ini.  This is done to make performance fast, even with hundreds of settings. 
 *
 * PHP versions 5
 *
 * Zuha(tm) : Business Management Applications (http://zuha.com)
 * Copyright 2009-2010, Zuha Foundation Inc. (http://zuha.org)
 *
 * Licensed under GPL v3 License
 * Must retain the above copyright notice and release modifications publicly.
 *
 * @copyright     Copyright 2009-2010, Zuha Foundation Inc. (http://zuha.com)
 * @link          http://zuha.com Zuha™ Project
 * @package       zuha
 * @subpackage    zuha.app.models
 * @since         Zuha(tm) v 0.0.1
 * @license       GPL v3 License (http://www.gnu.org/licenses/gpl.html) and Future Versions
 */
class Setting extends AppModel {

	var $name = 'Setting';

	//The Associations below have been created with all possible keys, those that are not needed can be removed
	var $belongsTo = array(
		'SettingType' => array(
			'className' => 'Enumeration',
			'foreignKey' => 'type_id',
			'conditions' => array('SettingType.type' => 'SETTING_TYPE'),
			'fields' => '',
			'order' => ''
		)
	);
	
	
/**
 * Handles the saving of settings data to the settings.ini file
 *
 * @param {data}		An array contain the setting data
 * @param {bool}		If set to true, it will add to the value instead of replace.
 * @return {bool}		True if the settings were saved and the file was created.
 */
	function add($data, $append = false) {
		$data = $this->_cleanSettingData($data, $append);
		# save the data
		if ($this->save($data)) {
			# call all settings and write the ini file
			if($this->writeSettingsIniData()) {
				return true;
			} else {
				# roll back
				$this->delete($this->id);
				return false;
			}
		}
	}
	
	
/**
 * This function sets up the data from the settings table so that it will write a whole new file each time a setting is saved.
 *
 * return {string}		A string of data used to write to the settings.ini file.
 */
	function prepareSettingsIniData() {
		$settings = $this->find('all', array(
			'contain' => 'SettingType'
			));
		$writeData = '; Do not edit this file, instead go to /admin/settings and edit or add settings'.PHP_EOL.PHP_EOL;
		foreach ($settings as $setting) {
			if (strpos($setting['Setting']['value'], '=')) {
				$holdSettings[] = $setting;
			} else {
				$writeData .= '__';
				$writeData .= strtoupper($setting['SettingType']['name']);
				$writeData .= '_';
				$writeData .= strtoupper($setting['Setting']['name']);
				$writeData .= ' = ';
				$writeData .= $setting['Setting']['value'];
				$writeData .= PHP_EOL;
			}
		}
		
		$writeData .= $this->finishIniData($holdSettings);
		return $writeData;
	}
	
/**
 * We need to make sure that ini sections appear after all straight values in the ini file
 */
 	function finishIniData($settings) {
		foreach ($settings as $setting) {
			$writeData .= PHP_EOL.'[__';
			$writeData .= strtoupper($setting['SettingType']['name']);
			$writeData .= '_';
			$writeData .= strtoupper($setting['Setting']['name']).']'.PHP_EOL;
			$writeData .= $setting['Setting']['value'];
			$writeData .= PHP_EOL.PHP_EOL;
		}
		return $writeData;
	}
	
	
/**
 * This function sets up the data from the settings table so that it will write a whole new file each time a setting is saved.
 *
 * return {string}		A string of data used to write to the settings.ini file.
 */
	function writeSettingsIniData() {
		# move this inside of the save fi statement 
		App::import('Core', 'File');
		$file = new File;
		$file->path = CONFIGS.'settings.ini';
		$writeData = $this->prepareSettingsIniData();
		if($file->write($file->prepare($writeData))) {
			return true;
		} else {
			return false;
		}
	}
	
	
/**
 * Checks whether the setting already exists and cleans the data array if it does.
 * This is used mainly by outside of the model functions which don't know if the Setting exists or not.
 *
 * @param {array}		An array of Setting data
 */
	function _cleanSettingData($data, $append = false){
		#look up the type_id, if it isn't already set
		if (empty($data['Setting']['type_id'])) {
			$settingType = $this->SettingType->find('first', array(
				'conditions' => array(
					'SettingType.name' => $data['Setting']['typeName'],
					'SettingType.type' => 'SETTING_TYPE',
					),
				));
			# set the type id into the data array
			$data['Setting']['type_id'] = $settingType['SettingType']['id'];
		} 
		
		# see if the setting already exists
		$setting = $this->find('first', array(
			'conditions' => array(
				'Setting.name' => $data['Setting']['name'],
				'Setting.type_id' => $data['Setting']['type_id'],
				),
			));
		if(!empty($setting)) {
			# if it does, then set the id, so that we over write instead of creating a new setting
			$data['Setting']['id'] = $setting['Setting']['id'];
		}
		
		if (!empty($append) && !empty($setting)) {
			$data['Setting']['value'] = $setting['Setting']['value'].PHP_EOL.$data['Setting']['value'];
		}
		
		return $data;
	}
}
?>